FROM fedora:27

LABEL maintainer="Thomas Brown <tabsoftwareconsulting@gmail.com>"

RUN dnf -y update && dnf -y install \
    boost-devel \
    boost-build \
    cmake \
    doxygen \
    eigen3-devel \
    gcc \
    gcc-c++ \
    git \
    graphviz \
    make \
    pkg-config \
    python \
    python-devel \
    python-pip \
    zeromq-devel

# Clone, build, and install uhd
RUN git clone --branch v3.11.0.0 https://github.com/ettusresearch/uhd /tmp/uhd && \
    \
    pip install --user mako && \
    pip install --user requests && \
    rm -rf /tmp/uhd/host/build && \
    mkdir /tmp/uhd/host/build && \
    cd /tmp/uhd/host/build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DENABLE_C_API=OFF \
        -DENABLE_EXAMPLES=OFF \
        -DENABLE_UTILS=OFF \
        -DENABLE_TESTS=OFF \
        -DENABLE_MANUAL=OFF \
        -DENABLE_MAN_PAGES=OFF \
        -DENABLE_DOXYGEN=OFF \
        -DENABLE_USB=OFF \
        -DENABLE_GPSD=OFF \
        -DENABLE_E300=OFF \
        -DENABLE_N230=OFF \
        -DENABLE_MPMD=OFF \
        -DENABLE_OCTOCLOCK=OFF \
        /tmp/uhd/host && \
    cmake --build . && \
    cmake --build . --target install && \
    ldconfig /usr/local/lib && \
    cd / && \
    rm -rf /tmp/uhd && \
    pip uninstall -y mako && \
    pip uninstall -y requests

#RUN groupadd -g 10000 jenkins
RUN groupadd -g 117 jenkins
#RUN useradd -u 10000 -g jenkins jenkins
RUN useradd -u 113 -g jenkins jenkins

USER jenkins

ENV HOME /home/jenkins

WORKDIR /home/jenkins

# Set up Boost.Build
RUN echo "# DO NOT EDIT - generated by Dockerfile" > "${HOME}/user-config.jam"
RUN echo "import boost ;" >> "${HOME}/user-config.jam"
RUN echo "" >> "${HOME}/user-config.jam"
RUN echo "using gcc ;" >> "${HOME}/user-config.jam"
RUN echo "using doxygen ;" >> "${HOME}/user-config.jam"
RUN echo "using boost : \"\" : <include>/usr/include <library>/usr/lib <layout>system ;" >> "${HOME}/user-config.jam"
